import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="container">
      <h2 className="d-flex justify-content-center pb-2">Dashboard</h2>
      <div className="row">
        {/* Total Sales */}
        <div className="col-sm-12 col-md-6">
          <div className="card">
            <div className="card-header d-flex justify-content-between align-items-center">
              <h5>Total Sales Over Time</h5>

              <button className="btn btn-primary btn-sm">
                <Link to="/totalsales">View Details</Link>
              </button>
            </div>
            <div className="card-body">
              <div className="card-text">
                <p>
                  Displays the total revenue generated by sales over different
                  time intervals such as daily, monthly, quarterly, and yearly.
                  This provides an overview of how sales are performing over
                  time, helping to identify trends and seasonality in business
                  performance.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Sales Growth */}
        <div className="col-sm-12 col-md-6">
          <div className="card">
            <div className="card-header d-flex justify-content-between align-items-center">
              <h5>Sales Growth Rate Over Time</h5>
              <button className="btn btn-primary btn-sm">
                <Link to="/salesgrowth">View Details</Link>
              </button>
            </div>
            <div className="card-body">
              <div className="card-text">
                <p>
                  Measures the percentage change in sales over successive time
                  periods. It shows how fast or slow sales are growing, helping
                  to assess business momentum and identify opportunities for
                  growth or areas for improvement.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Cohort */}
        <div className="col-sm-12 col-md-6">
          <div className="card">
            <div className="card-header d-flex justify-content-between align-items-center">
              <h5>Customer Lifetime Value by Cohorts</h5>
              <button className="btn btn-primary btn-sm">
                <Link to="/cohort">View Details</Link>
              </button>
            </div>
            <div className="card-body">
              <div className="card-text">
                <p>
                  Groups customers based on the month of their first purchase
                  and calculates their total lifetime value. This helps in
                  understanding how valuable different customer groups are over
                  time and can inform strategies to increase retention and
                  lifetime value.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Customer Details */}
        <div className="col-sm-12 col-md-6">
          <div className="card">
            <div className="card-header d-flex justify-content-between align-items-center">
              <h5>Customers Details</h5>
              <button className="btn btn-primary btn-sm">
                <Link to="/customerdetails">View Details</Link>
              </button>
            </div>
            <div className="card-body">
              <div className="card-text">
                <p>
                  Tracks the number of new customers acquired over different
                  time intervals (daily, monthly, quarterly, yearly), providing
                  insights into acquisition trends and Identifies repeat
                  customers within the same time frames to assess loyalty and
                  retention strategies.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Customer City */}
        <div className="col-sm-12 col-md-6">
          <div className="card">
            <div className="card-header d-flex justify-content-between align-items-center">
              <h5>Geographical Distribution of Customers</h5>
              <button className="btn btn-primary btn-sm">
                <Link to="/customercity">View Details</Link>
              </button>
            </div>
            <div className="card-body">
              <div className="card-text">
                <p>
                  Visualizes customer locations by city, offering insights into
                  the geographical distribution of your customer base. This
                  helps identify key markets, regional trends, and potential
                  opportunities for business expansion and growth.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
